### ISSUE TITLE
City field is required for signup. 

### ISSUE THREAD

**Issue by CaseyDeriso** [JenniferFadare/D.O.G.S.#11]
<form class="signup-form">

            <div>

                <label for="username-signup">username:</label>

                <input type="text" id="username-signup" />

            </div>

            <div>

                <label for="email-signup">email:</label>

                <input type="text" id="email-signup" />

            </div>

            <div>

                <label for="password-signup">password:</label>

                <input type="password" id="password-signup" />

            </div>

            <div>

                <button type="submit">signup</button>

            </div>

        </form>

will need an additional field for the users city in order to make the fetch request to add a user to the db. 

in my fetch request, i have set it up to have the ID "city-signup", so 

            <div>
        
                <label for="city-signup">city</label>
        
                <input type="text" id="city-signup" />
        
            </div>

should work.

**Comment by peters0470** [comment]
got it fixed
